"""add category to courses

Revision ID: 52830eca69bb
Revises: ccbdc616a879
Create Date: 2026-03-22 12:52:09.140188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52830eca69bb'
down_revision = 'ccbdc616a879'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'category',
                sa.String(length=100),
                nullable=False,
                server_default="general"
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
